### ISSUE TITLE
Predicting ligands outside of the test set

### ISSUE THREAD

**Issue by jnoske** [CSUBioGroup/GraphscoreDTA#2]
Dear GraphscoreDTA developers,

Thank you for the excellent work. However, I was wondering how the trained model can be used to predict protein-ligand binding affinities for a protein-ligand pair that is not in the test set?

Thank you for your input.

**Comment by anotherras** [comment]
I have encountered the same problem, how can I solve it?  No code for processing data.

**Comment by messcode** [comment]
It would be very helpful if the authors can provide code for data processing.

**Comment by heshiyue1999** [comment]
> It would be very helpful if the authors can provide code for data processing.

Is the data preprocessing part implemented?

**Comment by anxiangbiye1231** [comment]
> > It would be very helpful if the authors can provide code for data processing.
> 
> Is the data preprocessing part implemented?
1. For the drug clustering method, the label id of the data set is not given, only the trained model is released; 2. The input feature script of the preprocessed data set is not released. It is difficult to achieve the original experiment, and can not be used as a benchmark for performance comparison

**Comment by moranlin** [comment]
Can the author give me a pre-processing process? I can't predict my own data even if you only give the processed data.

**Comment by htumlc** [comment]
这个数据是提取完特征的吗？
